name: Build Java Project

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew build --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-artifact
          path: build/libs
